## Importing libraries 

In [28]:
from sklearn import datasets
import pandas as pd
from sklearn.cross_validation import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier

In [29]:
#We've defined the three gases that we have considered and the class is the diseases caused/ aggrevated by the 
#composition of the gases / the environment.
names  = ['CO2','O2','N2','class']

## Creating a dataframe which stores the data in a table 

In [40]:
df = pd.read_csv('/Users/Varun/Desktop/d1c124.csv',header = None,names = names)
df.head()

CO2    O2    N2      class
0  25.88  3.93  5.71  gas_intox
1  25.77  3.95  5.03  gas_intox
2  25.21  2.98  5.70  gas_intox
3  24.98  3.23  5.03  gas_intox
4  24.95  3.80  5.72  gas_intox

In [31]:
import numpy as np
X = np.array(df[['CO2','O2','N2']])#features 
y = np.array(df['class'])#target
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.33)
knn = KNeighborsClassifier(n_neighbors = 3)#We've assigned the number of neighbours as an odd number to improve accuracy 
knn.fit(X_train,y_train)#Fitting the model
prediction = knn.predict(X_test)#predicts the disease if there is a high probability of it or 'perfect' if there is no disease 
#print X_test
print prediction

['cardiac' 'gas_intox' 'gas_intox' 'Perfect' 'Perfect' 'gas_intox'
 'gas_intox' 'cardiac' 'Perfect' 'emphysema' 'Perfect' 'Perfect' 'asthama'
 'Perfect' 'Perfect' 'Perfect' 'Perfect' 'gas_intox' 'Perfect' 'emphysema'
 'asthama' 'emphysema' 'emphysema' 'asthama' 'asthama' 'Perfect' 'Perfect'
 'asthama' 'Perfect' 'Perfect' 'asthama' 'gas_intox' 'Perfect' 'Perfect'
 'gas_intox' 'gas_intox' 'Perfect' 'Perfect' 'cardiac' 'Perfect' 'Perfect'
 'Perfect' 'Perfect' 'Perfect' 'asthama' 'Perfect' 'Perfect' 'gas_intox'
 'asthama' 'Perfect' 'Perfect' 'Perfect' 'Perfect' 'asthama' 'Perfect'
 'Perfect' 'Perfect' 'emphysema' 'gas_intox' 'Perfect' 'Perfect' 'Perfect'
 'Perfect' 'Perfect' 'Perfect' 'Perfect' 'Perfect' 'cardiac' 'Perfect'
 'Perfect' 'Perfect' 'cardiac' 'Perfect' 'Perfect' 'cardiac' 'Perfect'
 'Perfect' 'Perfect' 'Perfect' 'asthama' 'Perfect' 'Perfect' 'Perfect'
 'asthama' 'asthama' 'Perfect' 'Perfect' 'Perfect' 'Perfect' 'Perfect'
 'asthama' 'Perfect' 'Perfect' 'Perfect' 'Perfect' 'emphy

## Preprocessing data

In [32]:
type(y)

numpy.ndarray

In [33]:
X = np.array(df[['CO2','O2']])

In [34]:
X[:,0]

array([25.88, 25.77, 25.21, ..., 12.46,  9.4 ,  0.3 ])

In [35]:
X[:, 1]

array([3.93 , 3.95 , 2.98 , ..., 0.038, 0.082, 0.018])

In [36]:
y

array(['gas_intox', 'gas_intox', 'gas_intox', ..., 'Perfect', 'Perfect',
       'Perfect'], dtype=object)

In [37]:
X_test

array([[3.497e+01, 2.100e-01, 3.050e+00],
       [2.556e+01, 3.810e+00, 5.320e+00],
       [2.553e+01, 3.110e+00, 5.910e+00],
       ...,
       [1.517e+01, 9.800e-02, 7.400e-01],
       [9.530e+00, 7.200e-02, 5.700e-01],
       [1.251e+01, 2.000e-03, 2.600e-01]])

## Creating a numpy array with only one element. We need to reshape this to be able to put it into the predict function in case we have to predict for a single set of gas composition 

In [38]:
xxxx = np.array([0,0,0])

In [39]:
x1 = xxxx.reshape(1,-1)